// <auto-generated />
namespace MVC_2._2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class alpha10 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(alpha10));
        
        string IMigrationMetadata.Id
        {
            get { return "202405191916553_alpha1.0"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
